# -*- coding: utf-8 -*-
"""DataFrame.drop_duplicates.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10qEupM44GlcKZFyFBi_Ot7-HJOms-0zT
"""

import pandas as pd
df = pd.DataFrame({
    'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
    'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
    'rating': [4, 4, 3.5, 15, 5]
})
df

df.drop_duplicates()

df.drop_duplicates(subset=['brand'])

df.drop_duplicates(subset=['brand', 'style'], keep='last')