# -*- coding: utf-8 -*-
"""pandas.DataFrame.dropna.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TjB3HmGQy_V8ABi_czrrIzD2iCF5FyMr
"""

import pandas as pd
import numpy as np

df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy": [np.nan, 'Batmobile', 'Bullwhip'],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"),
                            pd.NaT]})
df

df.dropna()

df.dropna(axis='columns')

df.dropna(how='all')

df.dropna(thresh=2)

df.dropna(subset=['name', 'toy'])

df.dropna(inplace=True)
df

