# -*- coding: utf-8 -*-
"""pandas.DataFrame.replace.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rej-CCzYfIjpU8pTjAMboBQCOJ5zqaJX
"""

import pandas as pd
s = pd.Series([1, 2, 3, 4, 5])
s.replace(1, 5)

df = pd.DataFrame({'A': [0, 1, 2, 3, 4],
                   'B': [5, 6, 7, 8, 9],
                   'C': ['a', 'b', 'c', 'd', 'e']})
df.replace(0, 5)

df.replace([0, 1, 2, 3], 4)

df.replace([0, 1, 2, 3], [4, 3, 2, 1])

s.replace([1, 2], method='bfill')

df.replace({0: 10, 1: 100})

df.replace({'A': 0, 'B': 5}, 100)

df.replace({'A': {0: 100, 4: 400}})

df = pd.DataFrame({'A': ['bat', 'foo', 'bait'],
                   'B': ['abc', 'bar', 'xyz']})
df.replace(to_replace=r'^ba.$', value='new', regex=True)

df.replace({'A': r'^ba.$'}, {'A': 'new'}, regex=True)

df.replace(regex=r'^ba.$', value='new')

df.replace(regex={r'^ba.$': 'new', 'foo': 'xyz'})

df.replace(regex=[r'^ba.$', 'foo'], value='new')

s = pd.Series([10, 'a', 'a', 'b', 'a'])

s.replace({'a': None})

s.replace('a')

s.replace('a', None)

